name = "lapce-lsp-java"
version = "0.0.1"
author = "xiaoma20082008"
display-name = "Java"
description = "Java for Lapce: powered by Eclipse JDT Language Server"
wasm = "bin/lapce-lsp-java.wasm"
repository = "xiaoma20082008/lapce-lsp-java"

[activation]
language = ["java"]
workspace-contains = [
    # java file
    "**/*.java",
    # maven project
    "**/pom.xml",
    # gradle project
    "**/settings.gradle", "**/build.gradle.kts" ,
]

[config."lapce-lsp-java.serverPath"]
default = ""
description = "Path to custom LSP executable"

[config."lapce-lsp-java.serverArgs"]
default = []
description = ""

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
